# Dependabot configuration for automated dependency updates
# See: https://docs.github.com/en/code-security/dependabot

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "terragon-labs/core-team"
    assignees:
      - "terragon-labs/maintainers"
    labels:
      - "dependencies"
      - "python"
      - "security"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    # Group related updates
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"
      langchain-updates:
        patterns:
          - "langchain*"
      test-dependencies:
        patterns:
          - "pytest*"
          - "coverage"
          - "ruff"
          - "mypy"
          - "bandit"
      aws-dependencies:
        patterns:
          - "boto3"
          - "botocore"
    # Ignore specific packages that require manual updates
    ignore:
      - dependency-name: "apache-airflow"
        # Airflow updates often require migration steps
      - dependency-name: "numpy"
        versions: [">=2.0.0"]
        # NumPy 2.0+ may break compatibility

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "terragon-labs/devops-team"
    labels:
      - "dependencies"
      - "docker"
      - "infrastructure"
    commit-message:
      prefix: "build"
      include: "scope"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
      day: "first-monday"
      time: "11:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "terragon-labs/devops-team"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
    commit-message:
      prefix: "ci"
      include: "scope"