[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "agent_orchestrated_etl"
version = "0.0.1"
requires-python = ">=3.8"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["agent_orchestrated_etl"]

[project.scripts]
generate_dag = "agent_orchestrated_etl.cli:main"
run_pipeline = "agent_orchestrated_etl.cli:run_pipeline_cmd"
