apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-orchestrated-etl
  labels:
    app: agent-orchestrated-etl
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: agent-orchestrated-etl
  template:
    metadata:
      labels:
        app: agent-orchestrated-etl
        version: v1
    spec:
      containers:
      - name: agent-etl
        image: agent-orchestrated-etl:latest
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8080
          name: metrics
        env:
        - name: PYTHONPATH
          value: "/app/src"
        - name: AGENT_ETL_LOG_LEVEL
          value: "INFO"
        - name: AGENT_ETL_LOG_FORMAT
          value: "json"
        - name: AGENT_ETL_ENABLE_METRICS
          value: "true"
        - name: AGENT_ETL_ENABLE_SECURITY
          value: "true"
        - name: AGENT_ETL_ENABLE_ADAPTIVE
          value: "true"
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: REDIS_HOST
          value: "redis-service"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: config-volume
        configMap:
          name: agent-etl-config
      - name: data-volume
        persistentVolumeClaim:
          claimName: agent-etl-pvc
      imagePullSecrets:
      - name: registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: agent-etl-service
  labels:
    app: agent-orchestrated-etl
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  selector:
    app: agent-orchestrated-etl

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-etl-config
data:
  config.yaml: |
    database:
      host: postgres-service
      port: 5432
      name: agent_etl
      user: agent_etl_user
    cache:
      host: redis-service
      port: 6379
    logging:
      level: INFO
      format: json
    security:
      enable_audit: true
      enable_encryption: true
    performance:
      enable_metrics: true
      enable_adaptive: true
      max_workers: 10

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-etl-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: agent-etl-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agent-orchestrated-etl
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80