name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install .[dev]
      - name: Run tests
        run: |
          coverage run -m pytest -q
      - name: Coverage report
        run: coverage report -m
